"""Property-based tests for tab_conductor.plan_parser.

Uses Hypothesis to generate arbitrary plan structures and verify that:
1. Valid plans always parse without raising.
2. Invalid plans (bad priority, cycle, dup id) always raise PlanParseError.
3. redact_text never introduces new content (only replaces or leaves unchanged).
"""

from __future__ import annotations

import string
from typing import Any

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from tab_conductor.exceptions import PlanParseError
from tab_conductor.plan_parser import ParsedPlan, parse_plan_dict, redact_text

# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

_safe_str = st.text(
    alphabet=string.ascii_letters + string.digits + "_-",
    min_size=1,
    max_size=20,
)

_prompt_st = st.text(min_size=1, max_size=100).filter(lambda s: s.strip() != "")

_priority_st = st.integers(min_value=0, max_value=9)

_max_retries_st = st.integers(min_value=0, max_value=10)

_kind_st = st.sampled_from(["general", "refactor", "verify", "build"])


def _task_st(task_id: str) -> st.SearchStrategy[dict[str, Any]]:
    """Strategy for a valid task dict with the given id."""
    return st.fixed_dictionaries({
        "id": st.just(task_id),
        "prompt": _prompt_st,
        "kind": _kind_st,
        "priority": _priority_st,
        "max_retries": _max_retries_st,
        "depends_on": st.just([]),
    })


@st.composite
def _valid_plan_st(draw: st.DrawFn) -> dict[str, Any]:
    """Generate a valid plan dict with 1-5 tasks, no deps (avoids cycle complexity)."""
    n = draw(st.integers(min_value=1, max_value=5))
    # Generate unique ids
    ids = draw(
        st.lists(
            _safe_str,
            min_size=n,
            max_size=n,
            unique=True,
        )
    )
    tasks = [draw(_task_st(tid)) for tid in ids]
    return {
        "name": draw(_safe_str),
        "description": draw(_safe_str),
        "max_parallel": draw(st.integers(min_value=1, max_value=8)),
        "tasks": tasks,
    }


# ---------------------------------------------------------------------------
# Property 1: valid plans always parse
# ---------------------------------------------------------------------------


@given(plan=_valid_plan_st())
@settings(
    max_examples=40,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
    deadline=None,
)
def test_valid_plan_always_parses(plan: dict[str, Any]) -> None:
    """Any plan generated by _valid_plan_st() must parse without raising."""
    result = parse_plan_dict(plan)
    assert isinstance(result, ParsedPlan)
    assert len(result.tasks) == len(plan["tasks"])
    # Task ids must be preserved
    parsed_ids = {t["id"] for t in result.tasks}
    expected_ids = {t["id"] for t in plan["tasks"]}
    assert parsed_ids == expected_ids


# ---------------------------------------------------------------------------
# Property 2: out-of-range priority always raises
# ---------------------------------------------------------------------------


@given(
    priority=st.one_of(
        st.integers(max_value=-1),
        st.integers(min_value=10),
    )
)
@settings(max_examples=20, deadline=None)
def test_invalid_priority_always_raises(priority: int) -> None:
    """A task with priority outside [0,9] must always raise PlanParseError."""
    data = {"tasks": [{"id": "t", "prompt": "p", "priority": priority}]}
    with pytest.raises(PlanParseError, match="priority"):
        parse_plan_dict(data)


# ---------------------------------------------------------------------------
# Property 3: duplicate id always raises
# ---------------------------------------------------------------------------


@given(task_id=_safe_str)
@settings(max_examples=20, deadline=None)
def test_duplicate_id_always_raises(task_id: str) -> None:
    """Two tasks sharing the same id must always raise PlanParseError."""
    data = {
        "tasks": [
            {"id": task_id, "prompt": "first"},
            {"id": task_id, "prompt": "second"},
        ]
    }
    with pytest.raises(PlanParseError, match="Duplicate"):
        parse_plan_dict(data)


# ---------------------------------------------------------------------------
# Property 4: redact_text is idempotent (applying twice == applying once)
# ---------------------------------------------------------------------------


@given(text=st.text(min_size=0, max_size=200))
@settings(max_examples=40, deadline=None)
def test_redact_text_idempotent(text: str) -> None:
    """Applying redact_text twice must produce the same result as once."""
    once = redact_text(text)
    twice = redact_text(once)
    assert once == twice, f"redact_text not idempotent on {text!r}"


# ---------------------------------------------------------------------------
# Property 5: redact_text never makes output longer than input
# ---------------------------------------------------------------------------


@given(text=st.text(min_size=0, max_size=200))
@settings(max_examples=40, deadline=None)
def test_redact_text_never_grows(text: str) -> None:
    """redact_text must not produce output longer than input."""
    result = redact_text(text)
    assert len(result) <= len(text) + len("[REDACTED]"), (
        f"redact_text grew output unexpectedly: {len(text)} -> {len(result)}"
    )
